###
GET http://localhost:3500/api/status

###
GET http://localhost:3500/api/login

###
GET http://localhost:3500/api/register

###
GET http://localhost:3500/api/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk

###
POST http://localhost:3500/api/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk
Content-Type: application/json

{
  "name":"Raddison Blue",
  "type":"hotel",
  "city":"Mersin",
  "address":"somewhere",
  "distance":"500",
  "title":"Best Hotel in the City",
  "desc":"desccc",
  "cheapestPrice":100
}

###
POST http://localhost:3500/api/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk
Content-Type: application/json

{
  "name":"Lamos Hotel",
  "type":"hotel",
  "city":"Mersin",
  "address":"somewhere",
  "distance":"500",
  "title":"Best Hotel in the City",
  "desc":"desccc",
  "cheapestPrice":250
}


###
GET http://localhost:3500/api/hotels/64555297f39fd2407c9163bc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk

###
PUT http://localhost:3500/api/hotels/64555297f39fd2407c9163bc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk
Content-Type: application/json

{
  "desc":"NEW DESCC",
  "cheapestPrice":200
}

###
DELETE http://localhost:3500/api/hotels/64555297f39fd2407c9163bc


###
POST http://localhost:3500/api/register
Content-Type: application/json

{
  "username":"myrn",
  "email":"myrn@example.com",
  "password":"987654"
}

###
POST http://localhost:3500/api/login
Content-Type: application/json

{
  "email":"amy@example.com",
  "password":"123123"
}

###
POST http://localhost:3500/api/login
Content-Type: application/json

{
  "username":"myrn",
  "password":"987654"
}

###
GET http://localhost:3500/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk

###
GET http://localhost:3500/api/users/64660b99198422accfaeb172
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk

###
POST http://localhost:3500/api/users/6469fab65ef36dbbf23c58b0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk
Content-Type: application/json

{
  "password": "123123",
  "newPassword": "987654"
}

###
PUT http://localhost:3500/api/users/64660b99198422accfaeb173
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk
Content-Type: application/json

{
  "email":"myrn@example.com",
  "password": "123123"
}

###
DELETE http://localhost:3500/api/users/64660b99198422accfaeb173
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjlmYWI2NWVmMzZkYmJmMjNjNThiMCIsInVzZXJuYW1lIjoibXlybiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDY4MDk1NiwiZXhwIjoxNjg0NjgwOTg2fQ.uJPIR5d7qlvDnYzjQ_mmAgMk0zRdB8o0TvS8kv6U2bk
Content-Type: application/json

{
  "password": "123456"
}

###
GET http://localhost:3500/api/refresh/6469fab65ef36dbbf23c58b0

###
GET http://localhost:3500/api/logout
